### ISSUE TITLE
Athom 2.0.1 beta doesn't find file assets\icon.svg [Windows]

### ISSUE THREAD

**Issue by Dijker** [athombv/node-athom-cli#39]
updated to beta,
loged in . 
![image](https://user-images.githubusercontent.com/12412734/36318249-8c64a6b8-133f-11e8-9fb8-049c5cf71a9b.png)
The file is there....

Re-installed stable version and that worked without problem.

**Comment by WeeJeWel** [comment]
Should be fixed, please confirm.

**Comment by Dijker** [comment]
still the same, I guess  this test branch is the 2.0.3 and i Installed it....

`
D:\Homey\GitHub\nu.Dijker.PaperTrails>npm i -g athom-cli@beta
C:\Users\GDI.PQRNL\AppData\Roaming\npm\athom -> C:\Users\GDI.PQRNL\AppData\Roaming\npm\node_modules\athom-cli\bin\athom.js
**+ athom-cli@2.0.3**
added 111 packages, removed 161 packages, updated 23 packages and moved 1 package in 32.196s

D:\Homey\GitHub\nu.Dijker.PaperTrails>athom  homey select
┌──────────────────────────────────────────────────────────────────────────────────┐
│ Hey developer, we're hiring! View our open position at https://go.athom.com/jobs │
└──────────────────────────────────────────────────────────────────────────────────┘
? Choose an active Homey: BerliozHomeyR&D (online)
You have selected `BerliozHomeyR&D` as your active Homey.

D:\Homey\GitHub\nu.Dijker.PaperTrails>athom app  run
┌──────────────────────────────────────────────────────────────────────────────────┐
│ Hey developer, we're hiring! View our open position at https://go.athom.com/jobs │
└──────────────────────────────────────────────────────────────────────────────────┘
✓ Validating app...
**✘ Homey App did not validate against level `debug`:
Filepath does not exist: assets\icon.svg**
Not installing, please fix the validation issues first
`

**Comment by Dijker** [comment]
Dont know why it fails the validate, 

commented https://github.com/athombv/node-athom-cli/blob/c3636229d85fb3987713c997415edc571e33a828/lib/App/index.js#L85 to disable check and it works.....

Is the settings path intentional direct below Roaming and not in the npm\modules subfolder?
https://github.com/athombv/node-athom-cli/blob/c3636229d85fb3987713c997415edc571e33a828/lib/Settings/index.js#L26

// C:\Users\[username]\AppData\Roaming\**npm\node_modules**\athom-cli\
just one of the things I found in verifying all paths ....

couldn't fint the place it tests the assets\icon.svg file....

**Comment by WeeJeWel** [comment]
Fixed, please uninstall and install athom-cli again (the fix was applied in homey-lib)

**Comment by Dijker** [comment]
Confirmed works !!! Thanks!
